# Generated by Django 3.1 on 2020-08-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
